"""Core dataclasses and enums for Feather.

Split across :mod:`config_models`, :mod:`records`, and :mod:`runtime_models`;
this package re-exports the full surface so ``from feather.models import X``
resolves byte-identically for every existing importer (147 modules + both
subprocess entry points). The re-export is explicit (not ``import *``) so the
old module's leaked stdlib names (``datetime``/``Enum``/``field``/…) are no
longer part of the public surface — nothing imported them.
"""

from __future__ import annotations

from feather.models.config_models import (
    AgentConfig,
    AppConfig,
    ClaudeConfig,
    ClaudeThinkingConfig,
    CompactionConfig,
    DatabaseConfig,
    LoggingConfig,
    MCPConfig,
    MCPServerConfig,
    OpenAIConfig,
    OpenRouterConfig,
    OpenRouterTracingConfig,
    ParallelConfig,
    ReasoningConfig,
    SchedulerConfig,
    SelfRepairConfig,
    SkillsConfig,
    StorageConfig,
)
from feather.models.records import (
    AgentMessage,
    AgentMessageStatus,
    AttachmentKind,
    AttachmentRecord,
    CronJobRecord,
    CronJobStatus,
    CronScheduleType,
    LoadedSkill,
    MessageRole,
    PendingAttachment,
    PlanRecord,
    PlanStatus,
    SessionMessage,
    SessionRecord,
    SessionStatus,
    SkillMetadata,
    TaskEventRecord,
    TaskOutputKind,
    TaskOutputRecord,
    TaskRecord,
    TaskRunRecord,
    TaskRunStatus,
    TaskStatus,
    WorkerHeartbeat,
    WorkerStatus,
)
from feather.models.runtime_models import (
    AgentOutcome,
    AgentRunResult,
    EventHandler,
    EventKind,
    ModelTurn,
    ProviderRequestConfig,
    RuntimeEvent,
    ToolCall,
    ToolExecutionContext,
    ToolExecutionResult,
    ToolOutputArtifact,
    TraceContext,
)

__all__ = (
    # config_models
    "AgentConfig",
    "AppConfig",
    "ClaudeConfig",
    "ClaudeThinkingConfig",
    "CompactionConfig",
    "DatabaseConfig",
    "LoggingConfig",
    "MCPConfig",
    "MCPServerConfig",
    "OpenAIConfig",
    "OpenRouterConfig",
    "OpenRouterTracingConfig",
    "ParallelConfig",
    "ReasoningConfig",
    "SchedulerConfig",
    "SelfRepairConfig",
    "SkillsConfig",
    "StorageConfig",
    # records
    "AgentMessage",
    "AgentMessageStatus",
    "AttachmentKind",
    "AttachmentRecord",
    "CronJobRecord",
    "CronJobStatus",
    "CronScheduleType",
    "LoadedSkill",
    "MessageRole",
    "PendingAttachment",
    "PlanRecord",
    "PlanStatus",
    "SessionMessage",
    "SessionRecord",
    "SessionStatus",
    "SkillMetadata",
    "TaskEventRecord",
    "TaskOutputKind",
    "TaskOutputRecord",
    "TaskRecord",
    "TaskRunRecord",
    "TaskRunStatus",
    "TaskStatus",
    "WorkerHeartbeat",
    "WorkerStatus",
    # runtime_models
    "AgentOutcome",
    "AgentRunResult",
    "EventHandler",
    "EventKind",
    "ModelTurn",
    "ProviderRequestConfig",
    "RuntimeEvent",
    "ToolCall",
    "ToolExecutionContext",
    "ToolExecutionResult",
    "ToolOutputArtifact",
    "TraceContext",
)
